### ISSUE TITLE
Just to say Thanks

### ISSUE THREAD

**Issue by cgvirus** [samytichadou/Auto_Reload-Blender_addon#5]
Thanks for this real time saver. I have implemented it in my current research.
https://youtu.be/qcb8uoaDy4w

P.S: you can close this non-issue. :)

**Comment by kezzbracey** [comment]
Jumping in to say thanks as well.

This addon is exactly what I needed!

**Comment by samytichadou** [comment]
thanks guys ! glad the addon helps you :D
